""".env credential management: masked reads, validated writes, audited.

Security model (mirrors the project's trust model — whoever can open the
console can already read the .env file on disk):

* values are NEVER returned once stored — only "set" plus the last 4 chars;
* writes go through format validation per key kind, so a typo is rejected
  before it can waste a live session;
* the file is patched line-by-line: comments, ordering and unknown keys are
  preserved (python-dotenv round-trips would destroy them);
* every write appends an audit line to the console log — operation and key
  tail only, never values.
"""
from __future__ import annotations

import os
import re
import time
from typing import Dict, List, Optional

RE_PRIVATE_KEY = re.compile(r"^0x[0-9a-fA-F]{64}$")
# Lighter API keys: canonical form is 0x + 80 hex chars (40 bytes) as
# generated by lighter.create_api_key(); the SDK strips an optional 0x
# prefix before handing the string to the native signer, and 64-hex (32
# byte) keys are accepted for backwards compatibility. The authoritative
# check is signer.check_client() at engine start — this is shape-only.
RE_HEX_KEY = re.compile(r"^(?:0x)?(?:[0-9a-fA-F]{64}|[0-9a-fA-F]{80})$")
RE_ADDRESS = re.compile(r"^0x[0-9a-fA-F]{40}$")
RE_INT = re.compile(r"^\d+$")
# Katana API keys are UUIDs; the secret is an opaque token (uuid v4 at the
# time of writing — validate shape loosely: any non-empty printable token)
RE_UUID = re.compile(r"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-"
                     r"[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")
RE_TOKEN = re.compile(r"^[A-Za-z0-9_\-]{16,}$")

# key -> (kind, description)
KEY_KINDS: Dict[str, str] = {
    "HL_PRIVATE_KEY": "private_key",
    "HL_ACCOUNT_ADDRESS": "address",
    "HL_PRIVATE_KEY_XYZ": "private_key",
    "HL_ACCOUNT_ADDRESS_XYZ": "address",
    "LIGHTER_ACCOUNT_INDEX": "int",
    "LIGHTER_API_KEY_INDEX": "int",
    "LIGHTER_API_PRIVATE_KEY": "hex_key",
    # optional per-leg overrides: the two zkLighter deployments (mainnet vs
    # Robinhood) are separate accounts, so a base leg on Lighter-mainnet can
    # coexist with a lighter-rh hedge worker. Unset → shared LIGHTER_* wins.
    "LIGHTER_BASE_ACCOUNT_INDEX": "int",
    "LIGHTER_BASE_API_KEY_INDEX": "int",
    "LIGHTER_BASE_API_PRIVATE_KEY": "hex_key",
    "LIGHTER_HEDGE_ACCOUNT_INDEX": "int",
    "LIGHTER_HEDGE_API_KEY_INDEX": "int",
    "LIGHTER_HEDGE_API_PRIVATE_KEY": "hex_key",
    "KATANA_API_KEY": "uuid",
    "KATANA_API_SECRET": "token",
    "KATANA_PRIVATE_KEY": "private_key",
    "KATANA_WALLET": "address",
}

# what each hedge choice needs to be tradeable (creds_complete semantics)
VENUE_REQUIREMENTS: Dict[str, List[str]] = {
    "entropy": ["HL_PRIVATE_KEY"],
    "tradexyz": ["HL_PRIVATE_KEY"],   # XYZ keys optional overrides
    "lighter": ["LIGHTER_ACCOUNT_INDEX", "LIGHTER_API_KEY_INDEX",
                "LIGHTER_API_PRIVATE_KEY"],
    "lighter-rh": ["LIGHTER_ACCOUNT_INDEX", "LIGHTER_API_KEY_INDEX",
                   "LIGHTER_API_PRIVATE_KEY"],
    "katana": ["KATANA_API_KEY", "KATANA_API_SECRET", "KATANA_PRIVATE_KEY"],
}

# the same requirements under a per-leg override name, tried first
_LIGHTER_LEG_REQUIREMENTS: Dict[str, List[str]] = {
    "lighter-base": ["LIGHTER_BASE_ACCOUNT_INDEX",
                     "LIGHTER_BASE_API_KEY_INDEX",
                     "LIGHTER_BASE_API_PRIVATE_KEY"],
    "lighter-hedge": ["LIGHTER_HEDGE_ACCOUNT_INDEX",
                      "LIGHTER_HEDGE_API_KEY_INDEX",
                      "LIGHTER_HEDGE_API_PRIVATE_KEY"],
}


def _hex_key_error(value: str) -> str:
    """Explain why a Lighter-style key failed the format check.

    Describes only the SHAPE (length, prefix, character classes) — never
    echoes any character of the value itself."""
    s = value.strip()
    why = []
    if s.startswith("0X"):
        why.append("'0X' prefix — use lowercase '0x' or remove it")
    if re.search(r"\s", s):
        why.append("contains a space/line break (copy may have wrapped)")
    body = s[2:] if s.startswith("0x") else s
    if s.startswith("0x") and len(body) == 0:
        why.append("only a 0x prefix, no key body")
    nonhex = sum(1 for c in body if c not in "0123456789abcdefABCDEF")
    if nonhex:
        why.append(f"{nonhex} non-hex character(s) in the body")
    if len(body) not in (64, 80):
        why.append(f"body is {len(body)} chars, need 64 or 80")
    return ("expect 64 or 80 hex chars, optional 0x prefix"
            + ("; " + "; ".join(why) if why else ""))


def validate_value(key: str, value: str) -> Optional[str]:
    """Return an error message, or None when the value is well-formed."""
    kind = KEY_KINDS.get(key)
    if kind is None:
        return "unknown key"
    if kind == "private_key" and not RE_PRIVATE_KEY.match(value):
        return "expect 0x + 64 hex chars (agent wallet private key)"
    if kind == "hex_key" and not RE_HEX_KEY.match(value):
        return _hex_key_error(value)
    if kind == "address" and not RE_ADDRESS.match(value):
        return "expect 0x + 40 hex chars (main account address)"
    if kind == "int" and not RE_INT.match(value):
        return "expect an integer"
    if kind == "uuid" and not RE_UUID.match(value):
        return "expect a UUID (API key from the Katana Perps API keys page)"
    if kind == "token" and not RE_TOKEN.match(value):
        return "expect the API secret token (shown once when the key was created)"
    return None


def _line_pattern(key: str):
    return re.compile(rf"^(\s*)(?:export\s+)?{re.escape(key)}\s*=(.*)$")


class SecretsManager:
    def __init__(self, env_path: str, audit_log=None) -> None:
        self.env_path = env_path
        self._audit = audit_log   # callable(str), already value-free

    # ------------------------------------------------------------------ read

    def _raw(self) -> Optional[str]:
        try:
            with open(self.env_path) as fh:
                return fh.read()
        except FileNotFoundError:
            return None

    def status(self) -> dict:
        raw = self._raw()
        values = self._parse(raw) if raw is not None else {}
        keys = {}
        for key, kind in KEY_KINDS.items():
            v = values.get(key)
            keys[key] = {
                "set": v is not None,
                "tail": (v[-4:] if v is not None and len(v) >= 4
                         else ("···" if v is not None else None)),
                "kind": kind,
                "valid": None if v is None else validate_value(key, v) is None,
                "error": None if v is None else validate_value(key, v),
            }
        venues = {}
        for venue, reqs in VENUE_REQUIREMENTS.items():
            venues[venue] = all(values.get(k) for k in reqs)
        # per-leg lighter view: the leg-specific triple when present,
        # otherwise whatever the shared triple provides (mirrors
        # config.lighter_creds, so the live pre-flight agrees with the
        # engine's own startup check)
        for leg, reqs in _LIGHTER_LEG_REQUIREMENTS.items():
            venues[leg] = (all(values.get(k) for k in reqs)
                           if any(values.get(k) for k in reqs)
                           else venues["lighter"])
        return {"exists": raw is not None, "keys": keys, "venues": venues}

    def _parse(self, raw: str) -> Dict[str, str]:
        out = {}
        for ln in raw.splitlines():
            m = re.match(r"^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=(.*)$",
                         ln)
            if m:
                v = m.group(2).strip().strip('"').strip("'")
                out[m.group(1)] = v
        return out

    # ----------------------------------------------------------------- write

    def update(self, updates: Dict[str, str]) -> dict:
        """Set keys to new values; empty string deletes the key's line.
        Rejects the whole batch if any value is malformed."""
        errors = {}
        for key, val in (updates or {}).items():
            if key not in KEY_KINDS:
                errors[key] = "unknown key"
                continue
            val = (val or "").strip()
            if val == "":
                continue                    # delete — always allowed
            err = validate_value(key, val)
            if err:
                errors[key] = err
        if errors:
            return {"ok": False, "errors": errors, "status": self.status()}

        raw = self._raw()
        lines = raw.splitlines() if raw is not None else [
            "# entropy-arb credentials / 密钥配置",
            "# created by the web console — never commit this file",
            "",
        ]
        applied = []
        for key, val in (updates or {}).items():
            val = (val or "").strip()
            pat = _line_pattern(key)
            replaced = False
            for i, ln in enumerate(lines):
                if pat.match(ln):
                    if not replaced and val:
                        lines[i] = f"{key}={val}"
                        replaced = True
                    elif replaced or not val:
                        lines.pop(i)
            if val and not replaced:
                lines.append(f"{key}={val}")
            applied.append((key, val))

        content = "\n".join(lines) + "\n"
        d = os.path.dirname(os.path.abspath(self.env_path))
        os.makedirs(d, exist_ok=True)
        with open(self.env_path, "w") as fh:
            fh.write(content)
        try:
            os.chmod(self.env_path, 0o600)
        except OSError:
            pass
        for key, val in applied:
            self._audit(f"secrets: {key} "
                        + ("cleared" if not val else f"set ····{val[-4:]}"))
        return {"ok": True, "errors": {}, "status": self.status()}


def mask_updates_for_audit(updates: Dict[str, str]) -> str:
    """Human-safe summary of an update batch (for request logging)."""
    parts = []
    for k, v in (updates or {}).items():
        v = (v or "").strip()
        parts.append(f"{k}={'<clear>' if not v else '····' + v[-4:]}")
    return " ".join(parts)


def audit_writer(log_path: str):
    """Append-only audit log helper shared by console modules."""
    def write(msg: str) -> None:
        d = os.path.dirname(os.path.abspath(log_path))
        os.makedirs(d, exist_ok=True)
        with open(log_path, "a") as fh:
            fh.write(f"{time.strftime('%Y-%m-%d %H:%M:%S')} {msg}\n")
    return write
