/* Console V2 i18n strings — registered into the shared translator so the
   old page and V2 share one language selection mechanism. */
import { registerStrings } from "/static/i18n.js";

registerStrings({
  en: {
    "v2.brand": "strategy workbench",
    "v2.nav.decisions": "Strategy judgement",
    "v2.nav.ops": "Operations & access",
    "v2.nav.strategies": "Overview",
    "v2.nav.detail": "Strategy review",
    "v2.nav.experiments": "Adjust & verify",
    "v2.nav.accounts": "Accounts & risk",
    "v2.nav.runs": "Runs",
    "v2.nav.connections": "Exchange access / API Keys",
    "v2.nav.profiles": "Strategy config",
    "v2.nav.research": "Data research",
    "v2.legacy": "Legacy console",

    // shared states
    "v2.state.loading": "loading…",
    "v2.state.error": "request failed",
    "v2.state.empty": "nothing here yet",
    "v2.state.no_data": "no data",
    "v2.state.partial": "partial data — some sources failed",
    "v2.state.retry": "retry",
    "v2.state.updated": "updated {t}",
    "v2.state.not_yet": "Delivered by task {task} of the V2 plan — this view is a placeholder that will not pretend to have data.",
    "v2.state.strategy_pending": "Persistent strategy identities land with the phase-B storage migration (V2-006). Until then this panel only lists live worker sessions; stopped strategies keep no strategy-level view yet.",

    // pnl presentation
    "v2.pnl.pending": "pending reconciliation",
    "v2.pnl.pending_hint": "No reconciled ledger exists for this period — an estimate or session MTM is NOT net profit and is shown separately, labelled.",
    "v2.pnl.covered": "reconciled",

    // overview
    "v2.ov.period_pnl": "Period net P&L",
    "v2.ov.funding_risk": "Funding & risk",
    "v2.ov.pending_items": "Needs attention",
    "v2.ov.strategies": "Strategies",
    "v2.ov.live_sessions": "Live worker sessions (temporary view)",
    "v2.ov.col.name": "name / legs",
    "v2.ov.col.type": "type",
    "v2.ov.col.state": "run state",
    "v2.ov.col.net": "period net P&L",
    "v2.ov.col.evidence": "evidence",
    "v2.ov.col.next": "next step",
    "v2.ov.evidence_none": "no reconciled ledger yet",
    "v2.ov.next_review": "open review",
    "v2.ov.maker": "maker-hedge",
    "v2.ov.taker": "taker basis",
    "v2.ov.no_workers": "No engines running. Start one from Runs.",
    "v2.ov.att_worker_down": "{n} worker(s) errored or exited",
    "v2.ov.att_creds": "credential groups incomplete: {keys}",
    "v2.ov.att_none": "no known open issues",

    // accounts
    "v2.acct.title": "Accounts & risk",
    "v2.acct.note": "Aggregated from RUNNING workers only (legacy /api/venues). Equity takes the max per exchange group — it does not prove account-level deduplication across deployments. Stopped engines' residual positions are not visible here yet (V2-003).",
    "v2.acct.exchanges": "By exchange (running workers)",
    "v2.acct.positions": "Positions (per engine leg)",
    "v2.acct.asof": "as of {t}",
    "v2.acct.mtm_note": "Session MTM resets on restart; realized-today is the legacy maker-hedge edge — neither is reconciled net profit.",

    // runs
    "v2.runs.title": "Runs",
    "v2.runs.col.worker": "worker",
    "v2.runs.col.run": "run id",
    "v2.runs.col.profile": "profile",
    "v2.runs.col.market": "base / symbol / hedge",
    "v2.runs.col.mode": "mode",
    "v2.runs.col.state": "process state",
    "v2.runs.col.uptime": "uptime",
    "v2.runs.col.actions": "actions",
    "v2.runs.logs": "logs",
    "v2.runs.none": "no workers",

    "v2.runs.col.proc_state": "process",
    "v2.runs.col.engine_state": "engine",
    "v2.runs.col.residual": "residual",
    "v2.runs.col.data_age": "feed",
    "v2.runs.unreachable": "unreachable (503)",
    "v2.runs.residual_check": "preview",
    "v2.runs.stop_confirm": "Stop {symbol}? Positions are NOT closed and new risk is not paused by Stop alone.",
    "v2.runs.restart_note": "Restart adopts the same profile / market / mode and creates a NEW run id; the old run stays in history.",
    "v2.runs.restart_warn": "A live restart re-arms the engine with the CURRENT profile content.",
    "v2.runs.record_copy": "record-only: records market data only — it does NOT simulate or send orders.",
    "v2.runs.preview_scope": "Flatten scope = these ACCOUNT-MARKET pairs (both legs, every position on them): {keys}",
    "v2.runs.preview_conflict": "OTHER running instances share this account-market",
    "v2.runs.preview_blocked": "Execution is blocked — resolve the conflicts / errors above, then regenerate the preview.",
    "v2.runs.preview_ok": "No conflicts. Execution will stop this engine first, wait for fresh feeds, then send reduce-only IOC orders on both legs.",
    "v2.runs.note": "Operations run through the backend operation service: locks, request-id idempotency and persisted results. A timeout means UNKNOWN — check the exchange before any retry.",

    // connections
    "v2.conn.title": "Exchange access / API Keys",
    "v2.conn.note": "Masked status only in this stage: edit / save / delete and per-deployment diagnostics migrate in V2-002. “valid” means format-valid, not that authentication succeeded.",
    "v2.conn.col.key": "key",
    "v2.conn.col.state": "state",
    "v2.conn.col.valid": "format",
    "v2.conn.col.tail": "tail",
    "v2.conn.venue_groups": "Deployment completeness (from the legacy status — a checkmark means required fields are non-empty, not authenticated)",
    "v2.conn.keys": "Stored keys",
    "v2.conn.set": "set ····{tail}",
    "v2.conn.unset": "not set",
    "v2.conn.invalid": "invalid format",
    "v2.conn.ok": "format ok",

    "v2.conn.title.lighter": "Lighter (mainnet \u2014 shared default triple)",
    "v2.conn.title.rh": "Lighter RH (shares the mainnet triple \u2014 not separate storage)",
    "v2.conn.title.base": "Lighter base-leg override (trading leg, not mainnet/RH)",
    "v2.conn.title.hedge": "Lighter hedge-leg override (trading leg, not mainnet/RH)",
    "v2.conn.source": "resolved credential source",
    "v2.conn.src_override": "leg override keys",
    "v2.conn.src_shared": "shared default triple",
    "v2.conn.src_set": "stored",
    "v2.conn.src_unset": "not set",
    "v2.conn.override_rule": "If any field of the override triple is filled, all three are required (engine resolution: override wins per field, then falls back to the shared triple).",
    "v2.conn.rh_shared": "Mainnet and RH are separate deployments / accounts, but this console stores ONE shared triple for both (spec \u00a75.3). Per-leg overrides live in their own cards.",
    "v2.conn.leave_blank": "leave blank to keep the stored value",
    "v2.conn.delete": "delete on save",
    "v2.conn.del_hint": "tick to delete this key when saving (a blank input alone never deletes)",
    "v2.conn.save_title": "Save credential changes",
    "v2.conn.will_set": "set new value",
    "v2.conn.will_clear": "DELETE stored value",
    "v2.conn.affected": "Running instances whose credentials come from these keys:",
    "v2.conn.affected_none": "No running instance uses these keys.",
    "v2.conn.no_restart": "Saving does NOT restart anything \u2014 running processes usually keep the credentials they loaded at start.",
    "v2.conn.diag_confirm": "order-path test will PLACE and CANCEL a far post-only order \u2014 tick to confirm",
    "v2.conn.diag_none": "no diagnostics recorded for this target",
    "v2.conn.diag_last": "last diagnostics",
    "v2.conn.diag_pass": "steps passed",
    "v2.conn.diag_fail": "failed",
    "v2.conn.diag_stale": "STALE \u2014 credentials changed after this run",
    "v2.conn.diag_stale_hint": "re-run to refresh",
    "v2.conn.env_missing": ".env does not exist yet.",

    // profiles
    "v2.prof.title": "Strategy config",
    "v2.prof.col.name": "profile",
    "v2.prof.col.market": "symbol / hedge / base",
    "v2.prof.col.mode": "strategy type",
    "v2.prof.col.updated": "updated",
    "v2.prof.col.actions": "actions",
    "v2.prof.col.state": "state",
    "v2.prof.view": "view YAML",
    "v2.prof.none": "no profiles",
    "v2.prof.note": "Read-only stage: create / edit / validate / versions land in V2-004.",
    "v2.prof.running": "running",

    "v2.res.abs_range": "absolute dates (start / end / timezone)",
    "v2.res.abs_note": "absolute range: pick dates (the end day is INCLUDED) in the timezone below; sent to the server as UTC [start, end) — filtering happens before any statistic",
    "v2.res.range_mode": "range mode",
    "v2.res.coverage": "actual coverage",
    "v2.res.gaps": "gaps",
    "v2.res.bt_scope": "minute-bar band model only — no maker queue, fill selection, real latency or funding simulation",
    "v2.res.scale": "peak x scale",
    "v2.res.history_title": "minute history (recorded premium & executable edges, fee-gross)",
    "v2.rt.title": "live engine view",
    "v2.rt.mtm_note": "Session MTM / entry edges on this page reset with the engine process and are NOT period net P&L.",
    "v2.runs.live_view": "live view",
    "v2.prof.mode_form": "visual form",
    "v2.prof.mode_yaml": "advanced YAML",
    "v2.prof.versions": "versions",
    "v2.prof.yaml_note": "Full-schema YAML, saved verbatim (comments kept). Market fields (symbol / hedge / base) live in the sidecar next to the file and are edited in the form mode.",
    "v2.prof.effect_hot": "thresholds hot-reload (~60 s) — shown as effective once the running engine snapshot confirms them",
    "v2.prof.effect_restart": "saved — a worker restart is required for these changes to apply",
    "v2.prof.effect_saved": "saved — no running worker on this profile",
    "v2.prof.affected_runs": "affected runs",
    "v2.prof.conflict": "config_conflict: the profile changed since you read it (auto-band or another editor) — reload to see the diff, then re-apply",
    "v2.prof.leave_dirty": "This editor has unsaved changes. Leave anyway?",
    "v2.prof.stay": "keep editing",
    "v2.prof.leave": "discard and leave",
    "v2.prof.pending_thresholds": "thresholds suggested by the Analyzer were filled into the form — they are a DRAFT until saved",


    // research
    "v2.res.title": "Data research",
    "v2.res.note": "Analyzer, band backtest, minute history and the absolute-date filters migrate in V2-005 — including the backend start/end support that the legacy relative-hours view lacks.",

    // detail
    "v2.det.title": "Strategy review",

    "v2.det.list_note": "Persistent strategies (phase-B identity store): a strategy survives restarts, retunes and worker deletion. Net P&L stays pending until the reconciled ledger exists.",
    "v2.det.back": "all strategies",
    "v2.det.col.name": "strategy",
    "v2.det.col.market": "market / legs",
    "v2.det.col.type": "type",
    "v2.det.col.runs": "runs",
    "v2.det.col.live": "live",
    "v2.det.col.net": "period net P&L",
    "v2.det.none": "no strategies yet — start a worker to create one",
    "v2.det.runs": "runs (process lifecycles)",
    "v2.det.evidence": "evidence",
    "v2.det.evidence_note": "no reconciled ledger yet — legacy CSVs are partial evidence",
    "v2.det.import": "import legacy trade CSVs",
    "v2.det.import_note": "imports the trade CSVs this profile declares (incl. .old rotations); incremental and idempotent by file+line",
    "v2.det.imported": "imported",
    "v2.det.bad_rows": "bad rows",
    "v2.det.import_partial": "Legacy rows carry no order ids / fees: they stay UNRESOLVED partial evidence, not a reconciled ledger.",
    "v2.det.import_no_profile": "no profile mapped to this strategy yet",
    "v2.det.mapping": "mapping",
    "v2.det.no_id": "Open a strategy from the Overview. A persistent strategy page needs the phase-B identity store (V2-006) — this view will not fabricate history from worker sessions.",

    // experiments
    "v2.exp.title": "Adjust & verify",
    "v2.exp.note": "Experiment drafts and the activation / rollback state machine are phase D (V2-014 / V2-015). Nothing here can modify a profile or place orders.",

    // time control
    "v2.time.today": "today",
    "v2.time.yesterday": "yesterday",
    "v2.time.d7": "last 7 days",
    "v2.time.custom": "custom",
    "v2.time.timezone": "timezone",
    "v2.time.custom_hint": "custom range includes the end day (local midnight to midnight); converted to UTC [start, end)",
  },
  zh: {
    "v2.brand": "策略工作台",
    "v2.nav.decisions": "策略判断",
    "v2.nav.ops": "运维与接入",
    "v2.nav.strategies": "总览",
    "v2.nav.detail": "策略复盘",
    "v2.nav.experiments": "调整与验证",
    "v2.nav.accounts": "账户与风险",
    "v2.nav.runs": "运行管理",
    "v2.nav.connections": "交易所接入 / API Key",
    "v2.nav.profiles": "策略配置",
    "v2.nav.research": "数据研究",
    "v2.legacy": "旧版控制台",

    "v2.state.loading": "加载中…",
    "v2.state.error": "请求失败",
    "v2.state.empty": "暂无内容",
    "v2.state.no_data": "无数据",
    "v2.state.partial": "部分数据 —— 部分来源请求失败",
    "v2.state.retry": "重试",
    "v2.state.updated": "更新于 {t}",
    "v2.state.not_yet": "该视图由 V2 计划任务 {task} 交付 —— 当前为占位页，不会伪装有数据。",
    "v2.state.strategy_pending": "持久策略身份在阶段 B 存储迁移（V2-006）后提供；此前这里只列出运行中的 worker 会话，停止的策略暂无策略级视图。",

    "v2.pnl.pending": "待核对",
    "v2.pnl.pending_hint": "该期间没有已核对的账本 —— 估算或会话 MTM 不是净收益，仅另行标注展示。",
    "v2.pnl.covered": "已核对",

    "v2.ov.period_pnl": "期间净收益",
    "v2.ov.funding_risk": "资金与风险",
    "v2.ov.pending_items": "待处理",
    "v2.ov.strategies": "策略",
    "v2.ov.live_sessions": "运行中的 worker 会话（临时视图）",
    "v2.ov.col.name": "名称 / 两腿",
    "v2.ov.col.type": "类型",
    "v2.ov.col.state": "运行状态",
    "v2.ov.col.net": "期间净收益",
    "v2.ov.col.evidence": "证据",
    "v2.ov.col.next": "下一步",
    "v2.ov.evidence_none": "尚无已核对账本",
    "v2.ov.next_review": "进入复盘",
    "v2.ov.maker": "maker 对冲",
    "v2.ov.taker": "双边吃单",
    "v2.ov.no_workers": "当前没有运行中的引擎。请到“运行管理”启动。",
    "v2.ov.att_worker_down": "{n} 个 worker 异常退出",
    "v2.ov.att_creds": "凭据组不完整：{keys}",
    "v2.ov.att_none": "暂无已知待处理事项",

    "v2.acct.title": "账户与风险",
    "v2.acct.note": "仅聚合运行中的 worker（沿用旧 /api/venues）。权益按交易所组取最大值 —— 不能证明跨部署的账户去重。停机实例的残仓此处暂不可见（V2-003 交付）。",
    "v2.acct.exchanges": "按交易所（运行中的 worker）",
    "v2.acct.positions": "持仓（按引擎腿）",
    "v2.acct.asof": "截至 {t}",
    "v2.acct.mtm_note": "会话 MTM 重启即清零；“今日已实现”是旧版 maker 对冲 edge —— 两者都不是已核对的净收益。",

    "v2.runs.title": "运行管理",
    "v2.runs.col.worker": "worker",
    "v2.runs.col.run": "run id",
    "v2.runs.col.profile": "配置",
    "v2.runs.col.market": "基准腿 / 品种 / 对冲腿",
    "v2.runs.col.mode": "模式",
    "v2.runs.col.state": "进程状态",
    "v2.runs.col.uptime": "运行时长",
    "v2.runs.col.actions": "操作",
    "v2.runs.logs": "日志",
    "v2.runs.none": "暂无 worker",

    "v2.runs.col.proc_state": "进程状态",
    "v2.runs.col.engine_state": "引擎状态",
    "v2.runs.col.residual": "残仓",
    "v2.runs.col.data_age": "行情",
    "v2.runs.unreachable": "不可达 (503)",
    "v2.runs.residual_check": "预检",
    "v2.runs.stop_confirm": "停止 {symbol}？停止不会平掉仓位，也不等于暂停新增风险。",
    "v2.runs.restart_note": "重启沿用同一配置 / 市场 / 模式并生成新 run id；旧 run 保留在历史中。",
    "v2.runs.restart_warn": "实盘重启会以当前配置内容重新武装引擎。",
    "v2.runs.record_copy": "仅采集：只记录行情，不模拟、不发送任何订单。",
    "v2.runs.preview_scope": "平仓范围 = 以下账户-市场对（两条腿、其上的全部仓位）：{keys}",
    "v2.runs.preview_conflict": "其他运行中的实例共用该账户-市场",
    "v2.runs.preview_blocked": "执行被阻止 —— 先处置上方冲突 / 错误，再重新生成预检。",
    "v2.runs.preview_ok": "无冲突。执行将先停本引擎、等行情就绪，再在两腿发送 reduce-only IOC 订单。",
    "v2.runs.note": "运维操作经后端操作服务执行：锁、request_id 幂等与持久化结果。超时 = 状态未知 —— 先核对交易所，再考虑下一步。",

    "v2.conn.title": "交易所接入 / API Key",
    "v2.conn.note": "本阶段仅展示掩码状态：编辑 / 保存 / 删除与分部署诊断在 V2-002 迁移。“格式正确”不代表鉴权成功。",
    "v2.conn.col.key": "键",
    "v2.conn.col.state": "状态",
    "v2.conn.col.valid": "格式",
    "v2.conn.col.tail": "尾号",
    "v2.conn.venue_groups": "部署完备度（来自旧版状态 —— 勾选表示必填字段非空，不表示鉴权通过）",
    "v2.conn.keys": "已存密钥",
    "v2.conn.set": "已设置 ····{tail}",
    "v2.conn.unset": "未设置",
    "v2.conn.invalid": "格式不正确",
    "v2.conn.ok": "格式正确",

    "v2.conn.title.lighter": "Lighter 主网（共用默认三项）",
    "v2.conn.title.rh": "Lighter RH（与主网共用同一份三项 —— 不是独立存储）",
    "v2.conn.title.base": "Lighter 基础腿覆盖（交易腿凭据，不是主网 / RH）",
    "v2.conn.title.hedge": "Lighter 对冲腿覆盖（交易腿凭据，不是主网 / RH）",
    "v2.conn.source": "实际解析的凭据来源",
    "v2.conn.src_override": "腿覆盖三项",
    "v2.conn.src_shared": "共用默认三项",
    "v2.conn.src_set": "已存储",
    "v2.conn.src_unset": "未设置",
    "v2.conn.override_rule": "覆盖三项任一已填则三项都必须完整（引擎解析：逐字段先取覆盖，再回退共用三项）。",
    "v2.conn.rh_shared": "主网与 RH 是两套部署 / 账户，但本控制台只存一份共用三项（规格 §5.3）。逐腿覆盖放在各自的卡片中。",
    "v2.conn.leave_blank": "留空表示保留已存值",
    "v2.conn.delete": "保存时删除",
    "v2.conn.del_hint": "勾选后保存才会删除该键（仅留空不会删除）",
    "v2.conn.save_title": "保存凭据变更",
    "v2.conn.will_set": "写入新值",
    "v2.conn.will_clear": "删除已存值",
    "v2.conn.affected": "以下运行中的实例使用这些密钥：",
    "v2.conn.affected_none": "没有运行中的实例使用这些密钥。",
    "v2.conn.no_restart": "保存不会自动重启 —— 运行中的进程通常仍使用启动时加载的密钥。",
    "v2.conn.diag_confirm": "订单路径测试会真实挂出一笔远处 post-only 并撤单 —— 勾选确认",
    "v2.conn.diag_none": "该目标暂无诊断记录",
    "v2.conn.diag_last": "上次诊断",
    "v2.conn.diag_pass": "阶段通过",
    "v2.conn.diag_fail": "失败",
    "v2.conn.diag_stale": "已过期 —— 诊断后凭据已更改",
    "v2.conn.diag_stale_hint": "请重新诊断",
    "v2.conn.env_missing": ".env 尚不存在。",

    "v2.prof.title": "策略配置",
    "v2.prof.col.name": "配置",
    "v2.prof.col.market": "品种 / 对冲腿 / 基准腿",
    "v2.prof.col.mode": "策略类型",
    "v2.prof.col.updated": "更新时间",
    "v2.prof.col.actions": "操作",
    "v2.prof.col.state": "状态",
    "v2.prof.view": "查看 YAML",
    "v2.prof.none": "暂无配置",
    "v2.prof.note": "只读阶段：新建 / 编辑 / 校验 / 版本在 V2-004 交付。",
    "v2.prof.running": "运行中",

    "v2.res.abs_range": "绝对日期（起 / 止 / 时区）",
    "v2.res.abs_note": "绝对区间：选择起止日期（含结束日）与时区；后端转换为 UTC [start, end)，先过滤再统计",
    "v2.res.range_mode": "区间模式",
    "v2.res.coverage": "实际覆盖",
    "v2.res.gaps": "缺口",
    "v2.res.bt_scope": "仅为分钟级带宽模型 —— 未模拟 maker 队列、成交选择、真实延迟与资金费",
    "v2.res.scale": "峰值 × 系数",
    "v2.res.history_title": "分钟历史（采集的溢价与可成交 edge，费前）",
    "v2.rt.title": "实时引擎视图",
    "v2.rt.mtm_note": "本页的会话 MTM / 入场边际随引擎进程重置 —— 不是期间净收益。",
    "v2.runs.live_view": "实时视图",
    "v2.prof.mode_form": "可视化表单",
    "v2.prof.mode_yaml": "高级 YAML",
    "v2.prof.versions": "版本历史",
    "v2.prof.yaml_note": "完整 schema 的 YAML，按原文保存（保留注释）。市场字段（品种 / 对冲腿 / 基准腿）存于配置旁的 sidecar，请在表单模式中修改。",
    "v2.prof.effect_hot": "阈值将热加载（约 60 秒）—— 待运行中引擎 snapshot 确认后才显示生效",
    "v2.prof.effect_restart": "已保存 —— 这些修改需要重启 worker 才生效",
    "v2.prof.effect_saved": "已保存 —— 该配置当前没有运行中的实例",
    "v2.prof.affected_runs": "受影响的运行",
    "v2.prof.conflict": "配置冲突：读取后该文件已被其他人修改（auto-band 或其他编辑器）—— 先重新加载查看差异，再重新应用",
    "v2.prof.leave_dirty": "编辑器有未保存的修改。仍要离开吗？",
    "v2.prof.stay": "继续编辑",
    "v2.prof.leave": "放弃并离开",
    "v2.prof.pending_thresholds": "分析工作台建议的阈值已填入表单 —— 保存前只是草稿",


    "v2.res.title": "数据研究",
    "v2.res.note": "分析工作台、带宽回测、分钟历史与绝对日期筛选在 V2-005 迁移 —— 包括旧版相对小时视图所缺的后端 start/end 支持。",

    "v2.det.title": "策略复盘",

    "v2.det.list_note": "持久策略（阶段 B 身份存储）：重启、调参、删除 worker 都不影响策略与历史。已核对账本建立前净收益保持待核对。",
    "v2.det.back": "全部策略",
    "v2.det.col.name": "策略",
    "v2.det.col.market": "市场 / 两腿",
    "v2.det.col.type": "类型",
    "v2.det.col.runs": "运行次数",
    "v2.det.col.live": "运行中",
    "v2.det.col.net": "期间净收益",
    "v2.det.none": "暂无策略 —— 启动一个 worker 后会自动创建",
    "v2.det.runs": "运行历史（进程生命周期）",
    "v2.det.evidence": "证据",
    "v2.det.evidence_note": "尚无已核对账本 —— 旧 CSV 属于部分证据",
    "v2.det.import": "导入历史成交流水",
    "v2.det.import_note": "导入该配置声明的成交流水（含 .old 轮转）；按文件+行增量幂等",
    "v2.det.imported": "已导入",
    "v2.det.bad_rows": "坏行",
    "v2.det.import_partial": "旧行没有订单号 / 手续费：保持未归因的部分证据状态，不是已核对账本。",
    "v2.det.import_no_profile": "该策略还没有关联的配置",
    "v2.det.mapping": "归属映射",
    "v2.det.no_id": "请从总览打开一个策略。持久策略页需要阶段 B 的身份存储（V2-006）—— 本视图不会用 worker 会话伪造历史。",

    "v2.exp.title": "调整与验证",
    "v2.exp.note": "实验草稿与启用 / 回退状态机为阶段 D（V2-014 / V2-015）。这里不会修改配置或发送订单。",

    "v2.time.today": "今天",
    "v2.time.yesterday": "昨天",
    "v2.time.d7": "近 7 天",
    "v2.time.custom": "自定义",
    "v2.time.timezone": "时区",
    "v2.time.custom_hint": "自定义包含结束日（当地零点到零点）；转换为 UTC [start, end)。",
  },
});
