/* Console V2 i18n strings — registered into the shared translator so the
   old page and V2 share one language selection mechanism. */
import { registerStrings } from "/static/i18n.js";

registerStrings({
  en: {
    "v2.brand": "strategy workbench",
    "v2.nav.decisions": "Strategy judgement",
    "v2.nav.ops": "Operations & access",
    "v2.nav.strategies": "Overview",
    "v2.nav.detail": "Strategy review",
    "v2.nav.experiments": "Adjust & verify",
    "v2.nav.accounts": "Accounts & risk",
    "v2.nav.runs": "Runs",
    "v2.nav.connections": "Exchange access / API Keys",
    "v2.nav.profiles": "Strategy config",
    "v2.nav.research": "Data research",
    "v2.legacy": "Legacy console",

    // shared states
    "v2.state.loading": "loading…",
    "v2.state.error": "request failed",
    "v2.state.empty": "nothing here yet",
    "v2.state.no_data": "no data",
    "v2.state.partial": "partial data — some sources failed",
    "v2.state.retry": "retry",
    "v2.state.updated": "updated {t}",
    "v2.state.not_yet": "Delivered by task {task} of the V2 plan — this view is a placeholder that will not pretend to have data.",
    "v2.state.strategy_pending": "Persistent strategy identities land with the phase-B storage migration (V2-006). Until then this panel only lists live worker sessions; stopped strategies keep no strategy-level view yet.",

    // pnl presentation
    "v2.pnl.pending": "pending reconciliation",
    "v2.pnl.pending_hint": "No reconciled ledger exists for this period — an estimate or session MTM is NOT net profit and is shown separately, labelled.",
    "v2.pnl.covered": "reconciled",

    // overview
    "v2.ov.period_pnl": "Period net P&L",
    "v2.ov.funding_risk": "Funding & risk",
    "v2.ov.pending_items": "Needs attention",
    "v2.ov.strategies": "Strategies",
    "v2.ov.live_sessions": "Live worker sessions (temporary view)",
    "v2.ov.col.name": "name / legs",
    "v2.ov.col.type": "type",
    "v2.ov.col.state": "run state",
    "v2.ov.col.net": "period net P&L",
    "v2.ov.col.evidence": "evidence",
    "v2.ov.col.next": "next step",
    "v2.ov.evidence_none": "no reconciled ledger yet",
    "v2.ov.next_review": "open review",
    "v2.ov.maker": "maker-hedge",
    "v2.ov.taker": "taker basis",
    "v2.ov.no_workers": "No engines running. Start one from Runs.",
    "v2.ov.att_worker_down": "{n} worker(s) errored or exited",
    "v2.ov.att_creds": "credential groups incomplete: {keys}",
    "v2.ov.att_none": "no known open issues",

    // accounts
    "v2.acct.title": "Accounts & risk",
    "v2.acct.note": "Aggregated from RUNNING workers only (legacy /api/venues). Equity takes the max per exchange group — it does not prove account-level deduplication across deployments. Stopped engines' residual positions are not visible here yet (V2-003).",
    "v2.acct.exchanges": "By exchange (running workers)",
    "v2.acct.positions": "Positions (per engine leg)",
    "v2.acct.asof": "as of {t}",
    "v2.acct.mtm_note": "Session MTM resets on restart; realized-today is the legacy maker-hedge edge — neither is reconciled net profit.",

    // runs
    "v2.runs.title": "Runs",
    "v2.runs.col.worker": "worker",
    "v2.runs.col.run": "run id",
    "v2.runs.col.profile": "profile",
    "v2.runs.col.market": "base / symbol / hedge",
    "v2.runs.col.mode": "mode",
    "v2.runs.col.state": "process state",
    "v2.runs.col.uptime": "uptime",
    "v2.runs.col.actions": "actions",
    "v2.runs.logs": "logs",
    "v2.runs.none": "no workers",
    "v2.runs.note": "Read-only migration stage: start / stop / restart / delete / flatten arrive with the operations service (V2-003) — use the legacy console for those actions meanwhile.",

    // connections
    "v2.conn.title": "Exchange access / API Keys",
    "v2.conn.note": "Masked status only in this stage: edit / save / delete and per-deployment diagnostics migrate in V2-002. “valid” means format-valid, not that authentication succeeded.",
    "v2.conn.col.key": "key",
    "v2.conn.col.state": "state",
    "v2.conn.col.valid": "format",
    "v2.conn.col.tail": "tail",
    "v2.conn.venue_groups": "Deployment completeness (from the legacy status — a checkmark means required fields are non-empty, not authenticated)",
    "v2.conn.keys": "Stored keys",
    "v2.conn.set": "set ····{tail}",
    "v2.conn.unset": "not set",
    "v2.conn.invalid": "invalid format",
    "v2.conn.ok": "format ok",
    "v2.conn.env_missing": ".env does not exist yet.",

    // profiles
    "v2.prof.title": "Strategy config",
    "v2.prof.col.name": "profile",
    "v2.prof.col.market": "symbol / hedge / base",
    "v2.prof.col.mode": "strategy type",
    "v2.prof.col.updated": "updated",
    "v2.prof.col.actions": "actions",
    "v2.prof.col.state": "state",
    "v2.prof.view": "view YAML",
    "v2.prof.none": "no profiles",
    "v2.prof.note": "Read-only stage: create / edit / validate / versions land in V2-004.",
    "v2.prof.running": "running",

    // research
    "v2.res.title": "Data research",
    "v2.res.note": "Analyzer, band backtest, minute history and the absolute-date filters migrate in V2-005 — including the backend start/end support that the legacy relative-hours view lacks.",

    // detail
    "v2.det.title": "Strategy review",
    "v2.det.no_id": "Open a strategy from the Overview. A persistent strategy page needs the phase-B identity store (V2-006) — this view will not fabricate history from worker sessions.",

    // experiments
    "v2.exp.title": "Adjust & verify",
    "v2.exp.note": "Experiment drafts and the activation / rollback state machine are phase D (V2-014 / V2-015). Nothing here can modify a profile or place orders.",

    // time control
    "v2.time.today": "today",
    "v2.time.yesterday": "yesterday",
    "v2.time.d7": "last 7 days",
    "v2.time.custom": "custom",
    "v2.time.timezone": "timezone",
    "v2.time.custom_hint": "custom range includes the end day (local midnight to midnight); converted to UTC [start, end)",
  },
  zh: {
    "v2.brand": "策略工作台",
    "v2.nav.decisions": "策略判断",
    "v2.nav.ops": "运维与接入",
    "v2.nav.strategies": "总览",
    "v2.nav.detail": "策略复盘",
    "v2.nav.experiments": "调整与验证",
    "v2.nav.accounts": "账户与风险",
    "v2.nav.runs": "运行管理",
    "v2.nav.connections": "交易所接入 / API Key",
    "v2.nav.profiles": "策略配置",
    "v2.nav.research": "数据研究",
    "v2.legacy": "旧版控制台",

    "v2.state.loading": "加载中…",
    "v2.state.error": "请求失败",
    "v2.state.empty": "暂无内容",
    "v2.state.no_data": "无数据",
    "v2.state.partial": "部分数据 —— 部分来源请求失败",
    "v2.state.retry": "重试",
    "v2.state.updated": "更新于 {t}",
    "v2.state.not_yet": "该视图由 V2 计划任务 {task} 交付 —— 当前为占位页，不会伪装有数据。",
    "v2.state.strategy_pending": "持久策略身份在阶段 B 存储迁移（V2-006）后提供；此前这里只列出运行中的 worker 会话，停止的策略暂无策略级视图。",

    "v2.pnl.pending": "待核对",
    "v2.pnl.pending_hint": "该期间没有已核对的账本 —— 估算或会话 MTM 不是净收益，仅另行标注展示。",
    "v2.pnl.covered": "已核对",

    "v2.ov.period_pnl": "期间净收益",
    "v2.ov.funding_risk": "资金与风险",
    "v2.ov.pending_items": "待处理",
    "v2.ov.strategies": "策略",
    "v2.ov.live_sessions": "运行中的 worker 会话（临时视图）",
    "v2.ov.col.name": "名称 / 两腿",
    "v2.ov.col.type": "类型",
    "v2.ov.col.state": "运行状态",
    "v2.ov.col.net": "期间净收益",
    "v2.ov.col.evidence": "证据",
    "v2.ov.col.next": "下一步",
    "v2.ov.evidence_none": "尚无已核对账本",
    "v2.ov.next_review": "进入复盘",
    "v2.ov.maker": "maker 对冲",
    "v2.ov.taker": "双边吃单",
    "v2.ov.no_workers": "当前没有运行中的引擎。请到“运行管理”启动。",
    "v2.ov.att_worker_down": "{n} 个 worker 异常退出",
    "v2.ov.att_creds": "凭据组不完整：{keys}",
    "v2.ov.att_none": "暂无已知待处理事项",

    "v2.acct.title": "账户与风险",
    "v2.acct.note": "仅聚合运行中的 worker（沿用旧 /api/venues）。权益按交易所组取最大值 —— 不能证明跨部署的账户去重。停机实例的残仓此处暂不可见（V2-003 交付）。",
    "v2.acct.exchanges": "按交易所（运行中的 worker）",
    "v2.acct.positions": "持仓（按引擎腿）",
    "v2.acct.asof": "截至 {t}",
    "v2.acct.mtm_note": "会话 MTM 重启即清零；“今日已实现”是旧版 maker 对冲 edge —— 两者都不是已核对的净收益。",

    "v2.runs.title": "运行管理",
    "v2.runs.col.worker": "worker",
    "v2.runs.col.run": "run id",
    "v2.runs.col.profile": "配置",
    "v2.runs.col.market": "基准腿 / 品种 / 对冲腿",
    "v2.runs.col.mode": "模式",
    "v2.runs.col.state": "进程状态",
    "v2.runs.col.uptime": "运行时长",
    "v2.runs.col.actions": "操作",
    "v2.runs.logs": "日志",
    "v2.runs.none": "暂无 worker",
    "v2.runs.note": "当前为只读迁移阶段：启动 / 停止 / 重启 / 删除 / 平仓随运维操作服务（V2-003）迁移 —— 此期间请用旧版控制台执行这些操作。",

    "v2.conn.title": "交易所接入 / API Key",
    "v2.conn.note": "本阶段仅展示掩码状态：编辑 / 保存 / 删除与分部署诊断在 V2-002 迁移。“格式正确”不代表鉴权成功。",
    "v2.conn.col.key": "键",
    "v2.conn.col.state": "状态",
    "v2.conn.col.valid": "格式",
    "v2.conn.col.tail": "尾号",
    "v2.conn.venue_groups": "部署完备度（来自旧版状态 —— 勾选表示必填字段非空，不表示鉴权通过）",
    "v2.conn.keys": "已存密钥",
    "v2.conn.set": "已设置 ····{tail}",
    "v2.conn.unset": "未设置",
    "v2.conn.invalid": "格式不正确",
    "v2.conn.ok": "格式正确",
    "v2.conn.env_missing": ".env 尚不存在。",

    "v2.prof.title": "策略配置",
    "v2.prof.col.name": "配置",
    "v2.prof.col.market": "品种 / 对冲腿 / 基准腿",
    "v2.prof.col.mode": "策略类型",
    "v2.prof.col.updated": "更新时间",
    "v2.prof.col.actions": "操作",
    "v2.prof.col.state": "状态",
    "v2.prof.view": "查看 YAML",
    "v2.prof.none": "暂无配置",
    "v2.prof.note": "只读阶段：新建 / 编辑 / 校验 / 版本在 V2-004 交付。",
    "v2.prof.running": "运行中",

    "v2.res.title": "数据研究",
    "v2.res.note": "分析工作台、带宽回测、分钟历史与绝对日期筛选在 V2-005 迁移 —— 包括旧版相对小时视图所缺的后端 start/end 支持。",

    "v2.det.title": "策略复盘",
    "v2.det.no_id": "请从总览打开一个策略。持久策略页需要阶段 B 的身份存储（V2-006）—— 本视图不会用 worker 会话伪造历史。",

    "v2.exp.title": "调整与验证",
    "v2.exp.note": "实验草稿与启用 / 回退状态机为阶段 D（V2-014 / V2-015）。这里不会修改配置或发送订单。",

    "v2.time.today": "今天",
    "v2.time.yesterday": "昨天",
    "v2.time.d7": "近 7 天",
    "v2.time.custom": "自定义",
    "v2.time.timezone": "时区",
    "v2.time.custom_hint": "自定义包含结束日（当地零点到零点）；转换为 UTC [start, end)。",
  },
});
